### ISSUE TITLE
ERROR in ./src/app/services/authentication.ts Module not found: Error: Cannot resolve 'file' or 'directory' ./../config.json when running npm run build

### ISSUE THREAD

**Issue by codelabspro** [joaogarin/angular2-electron#1]
==> npm run build

> angular2-electron@0.0.0 build /Users/coder/repos/codesdk/githubrepos/angular2-electron
> npm run build:dev
> 
> angular2-electron@0.0.0 build:dev /Users/coder/repos/codesdk/githubrepos/angular2-electron
> webpack --progress --profile --colors --display-error-details --display-cached

4935ms build modules  
21ms seal
44ms optimize
20ms hashing
57ms create chunk assets
2ms additional chunk assets 
1411ms optimize chunk assets
761ms optimize assets
45ms emit
Hash: a7d7fd54a52317de98f0
Version: webpack 1.13.0
Time: 7336ms
        Asset     Size  Chunks             Chunk Names
       app.js   937 kB       0  [emitted]  app
 polyfills.js   319 kB       1  [emitted]  polyfills
    vendor.js     1 MB       2  [emitted]  vendor
      app.map  1.09 MB       0  [emitted]  app
polyfills.map   399 kB       1  [emitted]  polyfills
   vendor.map  1.21 MB       2  [emitted]  vendor
 [346] external "electron" 42 bytes {0} [not cacheable]
       ... -> factory:2ms building:0ms
    + 639 hidden modules

ERROR in ./src/app/services/authentication.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ./../config.json in /Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/services
resolve file
  /Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json doesn't exist
  /Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.ts doesn't exist
  /Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.async.ts doesn't exist
  /Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.js doesn't exist
  /Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.async.js doesn't exist
  /Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.json doesn't exist
  /Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.async.json doesn't exist
  /Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.css doesn't exist
  /Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.async.css doesn't exist
  /Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.html doesn't exist
  /Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.async.html doesn't exist
resolve directory
  /Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json doesn't exist (directory default file)
  /Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json/package.json doesn't exist (directory description file)
[/Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json]
[/Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.ts]
[/Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.async.ts]
[/Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.js]
[/Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.async.js]
[/Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.json]
[/Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.async.json]
[/Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.css]
[/Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.async.css]
[/Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.html]
[/Users/coder/repos/codesdk/githubrepos/angular2-electron/src/app/config.json.async.html]
 @ ./src/app/services/authentication.ts 35:14-41

**Comment by KevinMcIntyre** [comment]
As the error and README suggests, a config.json file needs to be created in the app directory containing your GitHub API Token Info.

**Comment by joaogarin** [comment]
yes like @KevinMcIntyre is saying the config file needs to be created.
