### ISSUE TITLE
Packing application

### ISSUE THREAD

**Issue by TheAifam5** [joaogarin/angular2-electron#26]
How to use it with "electron-packager" or "electron-forge"?

**Comment by joaogarin** [comment]
Hello the repo has some integration with electron-packager. There are two scripts for this : 

npm run package https://github.com/joaogarin/angular2-electron/blob/master/package.json#L11

this will use the package.js file to package the application : https://github.com/joaogarin/angular2-electron/blob/master/package.js. The other script just passes --all flag to the package.js file (to package to all OS's) If you dont provide a "platform" flag to the command it will do it for "darwin" (OSX) by default.

You can about it in https://github.com/electron-userland/electron-packager

You can pass some options altough the defaults are already there for example for name and icon and stuff like that. The icon is the .icns file inside the app : https://github.com/joaogarin/angular2-electron/blob/master/src/app/app-icon.icns

I will try to put some documentation on this.

Best regards
Joao Garin

**Comment by joaogarin** [comment]
I will close this one, case there is some issue just feel free to reopen! =)
