### ISSUE TITLE
config.json is missing

### ISSUE THREAD

**Issue by MartinMajewski** [joaogarin/angular2-electron#29]
Error on run build:

```
ERROR in ./src/app/services/authentication.ts
Module not found: Error: Can't resolve './../config.json' in '/Users/martinmajewski/Documents/Development/ElectronApps/Angular2El
ectron/src/app/services'
 @ ./src/app/services/authentication.ts 32:14-41
 @ ./src/app/app.ts
```

**Comment by Vishal-Isharani** [comment]
yaa config.json in missing ....

**Comment by joaogarin** [comment]
Hello,

as mentioned in the readme file https://github.com/joaogarin/angular2-electron/blob/master/README.md you should create a config.json file. which includes sensitive information that I cant really put here..

It mentions there how the file should be formatted and what should be included there;) 

Best regards

**Comment by Xiltch** [comment]
I admit that i should have gone through the README.md first but like many other developers I suffer from impatience issues. 

I understand that being JSON you are unable to comment but you are able to scaffold the class with dummy data. 

That said, the project is awesome and well structured. Thank you.
