### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by SerG-Y** [joaogarin/angular2-electron#4]
I have some problem when I am building a project, using command "npm run build", because bundler cannot find the config.js which is required in authentication.ts in line 26. How can I  fix it ?
![error](https://cloud.githubusercontent.com/assets/12532719/18766939/4bea983e-8125-11e6-88e7-050f633e7fef.JPG)

**Comment by joaogarin** [comment]
Hello you can read in the readme file https://github.com/joaogarin/angular2-electron/blob/master/README.md how to set it up. Jus make a config.json similar to that, put your settings in there (private settings) and place it inside your src/app folder

**Comment by SerG-Y** [comment]
@joaogarin, Thank you!
