### ISSUE TITLE
packaget the application for all Platforms

### ISSUE THREAD

**Issue by anaji** [joaogarin/angular2-electron#42]
Hello,

I would like to packaging the project for windows but when i add the --all options,
I have only a packaging for OSX with this following line : 
Packaging app for platform darwin x64 using electron v1.4.15
null

Please could you tell me how to create a package for windows?

**Comment by joaogarin** [comment]
Hello,

This project uses https://github.com/electron-userland/electron-packager for packaging for all the platforms. For windows as far as I know you have to be on a Windows machine to be able to do it.

I will give it some tries to see what I can find. But if you find something else please feel free to report back;) You should be able to find this (where the package is being done) in this file https://github.com/joaogarin/angular2-electron/blob/master/package.js

**Comment by joaogarin** [comment]
I think to package to all platforms that needs to be done on windows, or edit some specific electron file, this is mentioned here : https://github.com/electron-userland/electron-packager#building-windows-apps-from-non-windows-platforms

**Comment by joaogarin** [comment]
Hello,

I just made a fix for the all package in https://github.com/joaogarin/angular2-electron/commit/1e649354f77440b89b206c9f2f9e39e93cedc522 . You have to set wine like mentioned in the previous comment or you will get an error : 'Make sure that the "wine" executable is in your PATH.'

Please let me know if it works well.

Best regards

**Comment by joaogarin** [comment]
You can install wine on MAC oS using homebrew : https://www.davidbaumgold.com/tutorials/wine-mac/#part-4:-install-wine-using-homebrew

**Comment by joaogarin** [comment]
Fixed in https://github.com/joaogarin/angular2-electron/commit/1e649354f77440b89b206c9f2f9e39e93cedc522
