### ISSUE TITLE
Windows Installer and AUto updater REquest 

### ISSUE THREAD

**Issue by Nebula-Spark** [joaogarin/angular2-electron#47]
Is it possible to add  windows installer and auto updater ?
Because Couldn't find any good repo or documentation to implement it ,
It would be great if u can add it on this repo.

**Comment by joaogarin** [comment]
Hello,

I would love to, but I not only am not comfortable with windows but even less comfortable with the windows app deployment system =/

I would love to integrate though if someone would be interested in contributing with such a thing ;)

Best regards

**Comment by Nebula-Spark** [comment]
I just Found  this blog and it's working Perfectly fine with auto update ,
 https://blog.avocode.com/blog/get-that-damn-windows-auto-update-working-on-electron
