### ISSUE TITLE
Firebase Storage ?

### ISSUE THREAD

**Issue by Nebula-Spark** [joaogarin/angular2-electron#57]
Is there Anyway to use firebase storage  ?
It's working Perfectly fine with angular-cli,

Using the following  code ,
Import *as firebase from 'firebase'

const storage =  firebase.strorage().ref()

Above Code Working FIne In webversion

But At node electron  getting the following error 

firebase.storeage is not a function !

Or Is there any good storage service can you recommend ?

**Comment by joaogarin** [comment]
```
firebase.storeage
```

Is that a typo? Its "storage". but to be quite frank I havent tried it, in web of electron version . I have used firebase with electron just as experiment, but failed in authenticating as previously it was not upported for electron..so I though it was not ideal. But maybe that works fine now.

**Comment by Nebula-Spark** [comment]
@joaogarin 

I just found the solution new version of firebase storage is not supported on nodejs , instead need to use  
@google-cloud/storage for file upload .
