### ISSUE TITLE
File to import not found or unreadable: @angular/material/core/theming/all-theme.

### ISSUE THREAD

**Issue by briosheje** [joaogarin/angular2-electron#65]
Had this issue on windows when running `npm run build`

Checked this:
https://github.com/angular/material2/issues/2277

So I've changed:

`@import '~@angular/material/core/theming/all-theme';`

to:

`@import '~@angular/material/theming';`

and it's working now. It looks like they have changed this lately (about 12 days ago)

**Comment by joaogarin** [comment]
Tks for the issue will take a look and update. I guess this is a newer version that introduced some breaking changes on material's side.

**Comment by briosheje** [comment]
@joaogarin Yep.

I also had to add `    "@angular/animations": "^4.0.0",` in the package.json, it was throwing an error when building, not sure whether it's still a change related to Angular Material itself :)

**Comment by joaogarin** [comment]
This should be fixed in https://github.com/joaogarin/angular-electron/commit/6bbcd1d5b21a7d0905a9fd64042c8dcf9f4c7985

**Comment by hemavidal** [comment]
I had the same problem today!

`ERROR in ./src/app/components/app.theme.scss
Module build failed:
@import '~@angular/material/core/theming/all-theme';
^
      File to import not found or unreadable: ~@angular/material/core/theming/all-theme.
Parent style sheet: stdin
      in C:\Users\hemav\Documents\angular2-electron\src\app\components\app.theme.scss (line 1, column 1)
 @ ./src/app/components/app.component.ts 31:17-44
 @ ./src/app/app.ts`

The code was changed in [joaogarin/angular-electron@6bbcd1d](https://github.com/joaogarin/angular-electron/commit/6bbcd1d5b21a7d0905a9fd64042c8dcf9f4c7985) but the problem still appear.

**Comment by briosheje** [comment]
@hemavidal 

you need to change app.theme.scss, replace:

`@import '~@angular/material/core/theming/all-theme';`

with 
`@import '~@angular/material/theming';`

if you check the code changes in https://github.com/joaogarin/angular-electron/commit/6bbcd1d5b21a7d0905a9fd64042c8dcf9f4c7985 he didn't (yet) change the .scss file.

**Comment by joaogarin** [comment]
Alright tks guys updated it here https://github.com/joaogarin/angular-electron/commit/91a841d72034ccbde9a34b6a939192651fac2105#diff-759ecc13f2ecebf5743fe0c5fd986262R1
