### ISSUE TITLE
Issue with Material Tabs: must include BrowserAnimationsModule 

### ISSUE THREAD

**Issue by briosheje** [joaogarin/angular2-electron#68]
Since some updates angular 2 material started using the BrowserAnimationsModule which must be included in order to use the Angular 2 material tabs (https://material.angular.io/components/component/tabs).

This needs to be added in the app.ts file
`import { BrowserAnimationsModule } from '@angular/platform-browser/animations';`

And injected in the `@NgModule`
```

@NgModule({
    imports: [
        BrowserModule,
        FormsModule,
        ReactiveFormsModule,
        HttpModule,
        BrowserAnimationsModule, // <--- here
```

Else an error will pop up and will prevent the execution of the next scripts :) (and tabs won't work)

**Comment by joaogarin** [comment]
Fixed in https://github.com/joaogarin/angular-electron/commit/6bbcd1d5b21a7d0905a9fd64042c8dcf9f4c7985

**Comment by joaogarin** [comment]
Thanks!;) :tada:

**Comment by briosheje** [comment]
@joaogarin Thank you for the beautiful starter, I'm using it a lot. Just a side question: are you having problem with karma aswell? I had to do several changes to the webpack.test.js and the karma config file to make it work, it usually throws me several errors whenever I try to test anything which has some electron-module included.
