### ISSUE TITLE
Packaging error (re-open)

### ISSUE THREAD

**Issue by Leonardonline** [joaogarin/angular2-electron#78]
I'm so sorry to reopen this bug, but I had the same error.

![image](https://user-images.githubusercontent.com/6098844/26893525-dcfd8d0c-4bbb-11e7-8bbe-531917890ce4.png)

I get this error running the EXE file of the app.
Instead running `npm run electron` command everythings work fine, also the md-slider.

**Comment by joaogarin** [comment]
I cant really reproduce this as I have no windows machine. Any chance you can try and find out what the issue is and maybe create a pull request?
That would be great.

**Comment by manxiaoboo** [comment]
Hi,I has a same problem with you. But I found a  way to solve it, maybe could help you.
Change the file 'package.js'
```
const DEFAULT_OPTS = {
    dir: './',//src/app
    name: appName,
    asar: shouldUseAsar,
    ignore: [
        '/release',
        '/config',
        '/node_modules'
    ].concat(devDeps.map(name => `/node_modules/${name}($|/)`))
};
```

**Comment by Leonardonline** [comment]
@manxiaoboo it works like a charm! Thank you so much!

**Comment by joaogarin** [comment]
Thanks for the feedback! Will try this to see if it can go into the repository. If it doesn't affect other packaging like OSX.

**Comment by manxiaoboo** [comment]
This method will pack more files into the program, not the best solution. We should just package the compiled JS files instead of all the source files and configuration files.

**Comment by zhuzhuojiang** [comment]
should only package the compiled JS files not include ts
