### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by mrfambo** [joaogarin/angular2-electron#79]
ERROR in ./src/app/services/authentication.ts
Module not found: Error: Can't resolve './../config.json' in 'C:\Users\FAMBO\Desktop\angular-electron-master\angular-electron-master\src\app\services'
 @ ./src/app/services/authentication.ts 33:14-41
 @ ./src/app/app.ts

> **Got this Error while Running the _npm run watch_ command.**

**Comment by joaogarin** [comment]
Hello you can find the information about the config file in the [README.md file ](https://github.com/joaogarin/angular-electron/blob/master/README.md)

You need to create that file.

Best regards
