### ISSUE TITLE
package @angular/cdk is needed.

### ISSUE THREAD

**Issue by zhanglongqi** [joaogarin/angular2-electron#86]
![image](https://user-images.githubusercontent.com/956693/27985042-e8bc8dce-6415-11e7-92bd-c2228d4bb7f1.png)

**Comment by 0x12eb** [comment]
@zhanglongqi try it :
`npm i--save @angular/material @angular/cdk`

**Comment by joaogarin** [comment]
Hello,

Have updated the repo today this should be fixed.
