### ISSUE TITLE
Global .scss file not workingq

### ISSUE THREAD

**Issue by divanvb** [joaogarin/angular2-electron#9]
Hi, I've set up my own custom theme in the global .scss file (app.theme.scss) but when the app goes the the login page, it's not picking up the theme. I have to manually place the theme content inside the login.component.scss file.

**Comment by divanvb** [comment]
Nevermind figured it out :)

**Comment by divanvb** [comment]
Nevermind it didnt work xD

**Comment by joaogarin** [comment]
hello,

if you want that sass file to be global and apply to all components, place it in the app component (root component) and set the component's view encapsulaton to none.

sample : 

``` javascript
import {ViewEncapsulation} from '@angular/core';

@Component({
  moduleId: module.id,
  selector: 'my-zippy',
  templateUrl: 'my-zippy.component.html',
  styles: [`
    .zippy {
      background: green;
    }
  `],
  encapsulation: ViewEncapsulation.None
})
class ZippyComponent {
  @Input() title: string;
}
```

https://angular.io/docs/ts/latest/guide/component-styles.html#!#view-encapsulation

**Comment by divanvb** [comment]
Thanks man you're a champion. We can close this discussion 💯

**Comment by joaogarin** [comment]
No problem! Glad I am able to help =) cheers!
